project_name: "HAI_Kaggle_ConvNeXt"
experiment_name: "convnext_base_clean"

data:
  # Kaggle path (Fixed)
  train_dir: "/kaggle/input/140k-real-and-fake-faces/real_vs_fake/real-vs-fake"
  val_dir: "/kaggle/input/140k-real-and-fake-faces/real_vs_fake/real-vs-fake"
  img_size: 224
  batch_size: 32
  num_workers: 2

model:
  backbone: "convnext_base"
  pretrained: true
  num_classes: 2
  dropout: 0.3

train:
  epochs: 10
  lr: 0.0001
  weight_decay: 1e-4
  scheduler: "CosineAnnealingLR"
  min_lr: 1e-6
  device: "cuda"
  save_dir: "checkpoints"
  log_interval: 100
